// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5klOKtdsiaEyrJ4EkHxF1P6ZzOZkBPME',
    appId: '1:751364244973:web:5f18284f20b176ef3f13e4',
    messagingSenderId: '751364244973',
    projectId: 'bbauth-9ef11',
    authDomain: 'bbauth-9ef11.firebaseapp.com',
    storageBucket: 'bbauth-9ef11.appspot.com',
    measurementId: 'G-Q58MXBT7TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkp8-uBldaVJxHaCrXeeMLCo6Yay599jo',
    appId: '1:751364244973:android:f4a4eb17745b75fe3f13e4',
    messagingSenderId: '751364244973',
    projectId: 'bbauth-9ef11',
    storageBucket: 'bbauth-9ef11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKR619gmJb37c9weXDF1CXAsRhTj1n7k',
    appId: '1:751364244973:ios:12e28e357161acb83f13e4',
    messagingSenderId: '751364244973',
    projectId: 'bbauth-9ef11',
    storageBucket: 'bbauth-9ef11.appspot.com',
    iosClientId: '751364244973-k3i146eipp1lp8evkt3panuehq2ep2vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bbAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqKR619gmJb37c9weXDF1CXAsRhTj1n7k',
    appId: '1:751364244973:ios:151b41b2da8360073f13e4',
    messagingSenderId: '751364244973',
    projectId: 'bbauth-9ef11',
    storageBucket: 'bbauth-9ef11.appspot.com',
    iosClientId: '751364244973-14tulnafubrucu4p98s49a6r9agb90af.apps.googleusercontent.com',
    iosBundleId: 'com.example.bbAuth.RunnerTests',
  );
}
